### ISSUE TITLE
Skyblock map

### ISSUE THREAD

**Issue by thediggyman** [lumien231/Perfect-Spawn#26]
World won't open with config:

---- Minecraft Crash Report ----

WARNING: coremods are present:
  StepupfixCore (StepupFix-1.12.2-1.0.0.4.jar)
  LoadingPlugin (PerfectSpawn-MC1.12.2-2.1.jar)
  TransformLoader (DynamicSurroundings-1.12.2-3.6.0.2.jar)
  CoreMod (Aroma1997Core-1.12.2-2.0.0.2.jar)
  TheBetweenlandsLoadingPlugin (TheBetweenlands-3.5.4-core.jar)
Contact their authors BEFORE contacting forge

// I'm sorry, Dave.

Time: 1/12/20 4:20 PM
Description: Exception in server tick loop

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Perfect Spawn (perfectspawn)
Caused by: com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Expected name at line 14 column 4 path $.rules[0].respawnDimension
	at com.google.gson.internal.Streams.parse(Streams.java:60)
	at com.google.gson.JsonParser.parse(JsonParser.java:84)
	at com.google.gson.JsonParser.parse(JsonParser.java:59)
	at lumien.perfectspawn.config.PSConfigHandler.loadConfig(PSConfigHandler.java:95)
	at lumien.perfectspawn.config.PSConfigHandler.reloadConfig(PSConfigHandler.java:61)
	at lumien.perfectspawn.config.PSConfigHandler.serverStarting(PSConfigHandler.java:39)
	at lumien.perfectspawn.PerfectSpawn.serverStarting(PerfectSpawn.java:44)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.serverStarting(Loader.java:792)
	at net.minecraftforge.fml.common.FMLCommonHandler.handleServerStarting(FMLCommonHandler.java:297)
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:158)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.google.gson.stream.MalformedJsonException: Expected name at line 14 column 4 path $.rules[0].respawnDimension
	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1559)
	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:505)
	at com.google.gson.stream.JsonReader.hasNext(JsonReader.java:414)
	at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:738)
	at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:731)
	at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:739)
	at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:714)
	at com.google.gson.internal.Streams.parse(Streams.java:48)
	... 40 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1815236608 bytes (1731 MB) / 3312451584 bytes (3159 MB) up to 7635730432 bytes (7282 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx8192m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.42 Powered by Forge 14.23.5.2831 65 mods loaded, 65 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State   | ID                             | Version       | Source                                        | Signature                                |
	|:------- |:------------------------------ |:------------- |:--------------------------------------------- |:---------------------------------------- |
	| LCHIJA  | minecraft                      | 1.12.2        | minecraft.jar                                 | None                                     |
	| LCHIJA  | mcp                            | 9.42          | minecraft.jar                                 | None                                     |
	| LCHIJA  | FML                            | 8.0.99.99     | forge-1.12.2-14.23.5.2831.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA  | forge                          | 14.23.5.2831  | forge-1.12.2-14.23.5.2831.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA  | aroma1997core                  | 2.0.0.2       | Aroma1997Core-1.12.2-2.0.0.2.jar              | dfbfe4c473253d8c5652417689848f650b2cbe32 |
	| LCHIJA  | nibbler                        | 0.4.1         | nibbler-1.12.2-0.4.1.jar                      | None                                     |
	| LCHIJA  | barkbooks                      | 1.2           | barkbooks-1.12.2-1.2.jar                      | None                                     |
	| LCHIJA  | baubles                        | 1.5.2         | Baubles-1.12-1.5.2.jar                        | None                                     |
	| LCHIJA  | bsb                            | 1.0           | BetweenlandsStorage.jar                       | None                                     |
	| LCHIJA  | redstoneflux                   | 2.1.0         | RedstoneFlux-1.12-2.1.0.6-universal.jar       | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCHIJA  | cofhcore                       | 4.6.3         | CoFHCore-1.12.2-4.6.3.27-universal.jar        | None                                     |
	| LCHIJA  | cofhworld                      | 1.3.1         | CoFHWorld-1.12.2-1.3.1.7-universal.jar        | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCHIJA  | jei                            | 4.15.0.291    | jei_1.12.2-4.15.0.291.jar                     | None                                     |
	| LCHIJA  | tombmanygraves                 | 1.12-4.2.0    | TombManyGraves-1.12-4.2.0.jar                 | None                                     |
	| LCHIJA  | tombmanygraves2api             | 1.12.2-1.0.0  | tombmanygraves2api-1.12.2-1.0.0.jar           | None                                     |
	| LCHIJA  | thebetweenlands                | 3.5.4         | TheBetweenlands-3.5.4-universal.jar           | 38067d6878811efb38b6a045521cfd80b9b60b38 |
	| LCHIJA  | betweenores                    | 1.4.2         | BetweenOres-1.4.2.jar                         | None                                     |
	| LCHIJA  | bookshelf                      | 2.3.590       | Bookshelf-1.12.2-2.3.590.jar                  | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA  | codechickenlib                 | 3.2.3.358     | CodeChickenLib-1.12.2-3.2.3.358-universal.jar | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA  | controlling                    | 3.0.7         | Controlling-3.0.7.jar                         | None                                     |
	| LCHIJA  | craftableglowstone             | 1.0           | craftableglowstone-1.12.2.jar                 | None                                     |
	| LCHIJA  | crafttweaker                   | 4.1.20        | CraftTweaker2-1.12-4.1.20.jar                 | None                                     |
	| LCHIJA  | ctgui                          | 1.0.0         | CraftTweaker2-1.12-4.1.20.jar                 | None                                     |
	| LCHIJA  | crafttweakerjei                | 2.0.3         | CraftTweaker2-1.12-4.1.20.jar                 | None                                     |
	| LCHIJA  | waila                          | 1.8.26        | Hwyla-1.8.26-B41_1.12.2.jar                   | None                                     |
	| LCHIJA  | darkutils                      | 1.8.230       | DarkUtils-1.12.2-1.8.230.jar                  | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA  | orelib                         | 3.6.0.1       | OreLib-1.12.2-3.6.0.1.jar                     | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| LCHIJA  | dsurround                      | 3.6.0.2       | DynamicSurroundings-1.12.2-3.6.0.2.jar        | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| LCHIJA  | dynamictrees                   | 1.12.2-0.9.6  | DynamicTrees-1.12.2-0.9.6.jar                 | None                                     |
	| LCHIJA  | roots                          | 1.12.2-3.0.21 | Roots-1.12.2-3.0.21.jar                       | None                                     |
	| LCHIJA  | dynamictreesroots              | 0.2.1         | dynamicTreesRoots-0.2.1.jar                   | None                                     |
	| LCHIJA  | eleccore                       | 1.9.453       | ElecCore-1.12.2-1.9.453.jar                   | None                                     |
	| LCHIJA  | erosion                        | 2.2.1         | Erosion-2.2.1.jar                             | None                                     |
	| LCHIJA  | gottschcore                    | 1.9.0         | GottschCore-mc1.12.2-f14.23.5.2768-v1.9.0.jar | None                                     |
	| LCHIJA  | fastladder                     | 1.1.1         | FastLadder-mc1.12.2-f14.23.5.2768-v1.1.1.jar  | None                                     |
	| LCHIJA  | fastleafdecay                  | v14           | FastLeafDecay-v14.jar                         | None                                     |
	| LCHIJA  | fastbench                      | 1.7.3         | FastWorkbench-1.12.2-1.7.3.jar                | None                                     |
	| LCHIJA  | gamestages                     | 2.0.115       | GameStages-1.12.2-2.0.115.jar                 | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA  | huds                           | #VERSION#     | Huds-1.12.2-1.0.6.jar                         | None                                     |
	| LCHIJA  | huskspawn                      | 1.0           | huskspawn_1.12-1.0.jar                        | None                                     |
	| LCHIJA  | ichunutil                      | 7.2.2         | iChunUtil-1.12.2-7.2.2.jar                    | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| LCHIJA  | inventorysorter                | 1.13.3+57     | inventorysorter-1.12.2-1.13.3+57.jar          | None                                     |
	| LCHIJA  | journeymap                     | 1.12.2-5.5.6  | journeymap-1.12.2-5.5.6.jar                   | None                                     |
	| LCHIJA  | jeresources                    | 0.9.2.60      | JustEnoughResources-1.12.2-0.9.2.60.jar       | None                                     |
	| LCHIJA  | leavestosaplings               | 3             | leavestosaplings-1.12.2-3.jar                 | None                                     |
	| LCHIJA  | magicclover                    | 1.12-0.7.8    | magicclover-1.12-0.7.8.jar                    | None                                     |
	| LCHIJA  | mobdismemberment               | 7.0.0         | MobDismemberment-1.12.2-7.0.0.jar             | None                                     |
	| LCHIJA  | monk                           | 1.4           | monk-mod-1.4.jar                              | None                                     |
	| LCHIJA  | moreoverlays                   | 1.15.1        | moreoverlays-1.15.1-mc1.12.2.jar              | None                                     |
	| LCHIJA  | mysticalworld                  | 1.12.2-1.6.1  | mysticalworld-1.12.2-1.6.1.jar                | None                                     |
	| LCHIJA  | nei                            | 2.4.3         | NotEnoughItems-1.12.2-2.4.3.245-universal.jar | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA  | patchouli                      | 1.0-20        | Patchouli-1.0-20.jar                          | None                                     |
	| LCHIJAE | perfectspawn                   | 2.1           | PerfectSpawn-MC1.12.2-2.1.jar                 | None                                     |
	| LCHIJA  | placebo                        | 1.6.0         | Placebo-1.12.2-1.6.0.jar                      | None                                     |
	| LCHIJA  | regrowableleaves               | 4.0.0         | regrowableleaves-1.12.2-4.0.0.jar             | None                                     |
	| LCHIJA  | stg                            | 1.12.2-1.2.3  | stg-1.12.2-1.2.3.jar                          | None                                     |
	| LCHIJA  | strayspawn                     | 1.0           | strayspawn_1.12-1.0.jar                       | None                                     |
	| LCHIJA  | tombmanypluginsthebetweenlands | 1.0.0         | tombmanypluginsthebetweenlands-1.0.0.jar      | None                                     |
	| LCHIJA  | totemic                        | 1.12.2-0.11.6 | Totemic-1.12.2-0.11.6.jar                     | 21d11d7bf4d97b465382a1f95428029aac6daaea |
	| LCHIJA  | wailastages                    | 2.0.24        | WailaStages-1.12.2-2.0.24.jar                 | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA  | waim                           | 1.0.0         | WAIM-1.0.0.jar                                | None                                     |
	| LCHIJA  | wawla                          | 2.5.273       | Wawla-1.12.2-2.5.273.jar                      | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA  | waystones                      | 4.0.72        | Waystones_1.12.2-4.0.72.jar                   | None                                     |
	| LCHIJA  | eleccoreloader                 | 1.9.453       | ElecCore-1.12.2-1.9.453.jar                   | None                                     |
	| LCHIJA  | mysticallib                    | 1.12.2-1.4.0  | mysticallib-1.12.2-1.4.0.jar                  | None                                     |

	Loaded coremods (and transformers): 
StepupfixCore (StepupFix-1.12.2-1.0.0.4.jar)
  
LoadingPlugin (PerfectSpawn-MC1.12.2-2.1.jar)
  lumien.perfectspawn.asm.ClassTransformer
TransformLoader (DynamicSurroundings-1.12.2-3.6.0.2.jar)
  
CoreMod (Aroma1997Core-1.12.2-2.0.0.2.jar)
  
TheBetweenlandsLoadingPlugin (TheBetweenlands-3.5.4-core.jar)
  thebetweenlands.core.TheBetweenlandsClassTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 0 / 8; []
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

[perfectspawn.txt](https://github.com/lumien231/Perfect-Spawn/files/4051496/perfectspawn.txt)

**Comment by remplerus** [comment]
theres missing respawn dimension 20, maybe adding this would work
```
{
  "appliesTo": [
    20
  ],
  "canRespawnHere": true,
  "respawnDimension": 20,
  "spawnPoint": {
    "poxX": 500,
    "poxY": 100,
    "poxZ": 400,
  }
}
```
